name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: test1
      run: echo "test1"

    - name: test2
      run: echo "test2"

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

---

name: Docker Image CI 2

on:
  pull_request:
    branches:
      - production
      
jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: node:16
      env:
        NODE_ENV: development
      options: --cpus 1
    steps:
      - name: test1
        run: echo "test1"
        
      - name: test2
        run: echo ${NODE_ENV}
